### ISSUE TITLE
DecisionTreeLearner fails on numeric attributes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#84]
```
What steps will reproduce the problem?

1. new DecisionTreeLearner().train(DataSetFactory.getIrisDataSet());

What is the expected output? What do you see instead?

Expected: green JUnit test bar
Instead: Red bar with Class Cast Exception

java.lang.ClassCastException: 
aima.core.learning.framework.NumericAttributeSpecification cannot be cast to 
aima.core.learning.framework.StringAttributeSpecification
    at aima.core.learning.framework.DataSetSpecification.getPossibleAttributeValues(DataSetSpecification.java:47)
    at aima.core.learning.framework.DataSet.getPossibleAttributeValues(DataSet.java:152)
    at aima.core.learning.learners.DecisionTreeLearner.decisionTreeLearning(DecisionTreeLearner.java:100)
    at aima.core.learning.learners.DecisionTreeLearner.train(DecisionTreeLearner.java:45)
    at de.pm.ext.aima.AimaTest.testName(AimaTest.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

What version of the product are you using?

version 0.10.5 from the Central Repository
```

Original issue reported on code.google.com by `andreas....@googlemail.com` on 15 May 2014 at 9:34

**Comment by shantanusinghal** [comment]
I've opened Pull Request #313 that attempts to solves this issue and I'd really appreciate some feedback on it.
